set_target_properties(${LIB_NAME} PROPERTIES PROJECT_LABEL ${PROJECT_NAME})
set_target_properties(${LIB_NAME} PROPERTIES VERSION ${WXGIS_VERSION})
set_target_properties(${LIB_NAME} PROPERTIES SOVERSION 1)

install(TARGETS ${LIB_NAME} DESTINATION ${LIB_INSTALL_PATH_DEBUG} CONFIGURATIONS Debug)
install(TARGETS ${LIB_NAME} DESTINATION ${LIB_INSTALL_PATH_RELEASE} CONFIGURATIONS Release)
if(NOT WIN32)
    install(FILES PROJECT_HHEADERS DESTINATION ${HEADERS_INSTALL_PATH})
endif(NOT WIN32)